INSERT INTO wasteCollection(binInfo_bin_type, postcode, collection_time) VALUES
('landfill', '3000', 'Every Thursday'),
('recyclable', '3000', 'Every Thursday'),
('landfill', '3001', 'Every Thursday'),
('recyclable', '3001', 'Every Thursday'),
('landfill', '3002', 'Every Friday'),
('recyclable', '3002', 'Every Friday'),
('landfill', '3003', 'Every Thursday'),
('recyclable', '3003', 'Every Thursday'),
('landfill', '3004', 'Every Thursday'),
('recyclable', '3004', 'Every Thursday'),
('landfill', '3006', 'Every Tuesday or Monday'),
('recyclable', '3006', 'Every Tuesday or Monday'),
('landfill', '3008', 'Every Thursday'),
('recyclable', '3008', 'Every Thursday'),
('landfill', '3013', 'Every Wednesday'),
('organics', '3013', 'Every Second Wednesday'),
('recyclable', '3013', 'Every Second Wednesday'),
('landfill', '3015', 'Every Thursday'),
('organics', '3015', 'Every Second Thursday'),
('recyclable', '3015', 'Every Second Thursday'),
('landfill', '3016', 'Every Thursday'),
('organics', '3016', 'Every Second Thursday'),
('recyclable', '3016', 'Every Second Thursday'),
('landfill', '3018', 'Every Friday'),
('organics', '3018', 'Every Second Friday'),
('recyclable', '3018', 'Every Second Friday'),
('landfill', '3028', 'Every Monday'),
('organics', '3028', 'Every Second Monday'),
('recyclable', '3028', 'Every Second Monday'),
('landfill', '3030', 'Every Monday'),
('organics', '3030', 'Every Second Monday'),
('recyclable', '3030', 'Every Second Monday'),
('landfill', '3031', 'Every Monday'),
('recyclable', '3031', 'Every Monday'),
('landfill', '3032', 'Every Monday'),
('recyclable', '3032', 'Every Monday'),
('landfill', '3051', 'Every Monday'),
('recyclable', '3051', 'Every Monday'),
('landfill', '3052', 'Every Monday'),
('recyclable', '3052', 'Every Monday'),
('landfill', '3053', 'Every Friday'),
('recyclable', '3053', 'Every Friday'),
('landfill', '3054', 'Every Friday'),
('recyclable', '3054', 'Every Friday'),
('landfill', '3060', 'Every Tuesday'),
('landfill', '3061', 'Every Monday'),
('organics', '3061', 'Every Second Monday'),
('recyclable', '3061', 'Every Second Monday'),
('landfill', '3064', 'Every Monday or Thursday'),
('organics', '3064', 'Every Second Monday'),
('recyclable', '3064', 'Every Second Monday or Thursday'),
('landfill', '3065', 'Every Friday'),
('recyclable', '3065', 'Every Friday'),
('landfill', '3073', 'Every Tuesday'),
('landfill', '3074', 'Every Monday'),
('organics', '3074', 'Every Second Monday'),
('recyclable', '3074', 'Every Second Monday'),
('landfill', '3075', 'Every Monday'),
('organics', '3075', 'Every Second Monday'),
('recyclable', '3075', 'Every Second Monday'),
('landfill', '3076', 'Every Monday'),
('landfill', '3081', 'Every Monday'),
('recyclable', '3081', 'Every Second Monday'),
('landfill', '3082', 'Every Friday'),
('organics', '3082', 'Every Second Friday'),
('recyclable', '3082', 'Every Second Friday'),
('landfill', '3083', 'Every Wednesday'),
('organics', '3083', 'Every Second Wednesday'),
('recyclable', '3083', 'Every Second Wednesday'),
('landfill', '3088', 'Every Wednesday'),
('organics', '3088', 'Every Second Wednesday'),
('recyclable', '3088', 'Every Second Wednesday'),
('landfill', '3090', 'Every Friday'),
('organics', '3090', 'Every Second Friday'),
('recyclable', '3090', 'Every Second Friday'),
('landfill', '3091', 'Every Friday'),
('organics', '3091', 'Every Second Friday'),
('recyclable', '3091', 'Every Second Friday'),
('landfill', '3099', 'Every Wednesday'),
('organics', '3099', 'Every Second Wednesday'),
('recyclable', '3099', 'Every Second Wednesday'),
('landfill', '3116', 'Every Thursday'),
('landfill', '3136', 'Every Thursday'),
('landfill', '3137', 'Every Monday'),
('landfill', '3138', 'Every Wednesday'),
('landfill', '3139', 'Every Friday'),
('landfill', '3143', 'Every Tuesday'),
('recyclable', '3143', 'Every Tuesday'),
('landfill', '3153', 'Every Monday'),
('landfill', '3154', 'Every Monday'),
('landfill', '3156', 'Every Monday'),
('landfill', '3158', 'Every Monday'),
('landfill', '3159', 'Every Friday'),
('landfill', '3160', 'Every Friday'),
('landfill', '3161', 'Every Tuesday'),
('recyclable', '3161', 'Every Tuesday'),
('landfill', '3169', 'Every Thursday'),
('landfill', '3171', 'Every Second Thursday'),
('landfill', '3172', 'Every Thursday'),
('landfill', '3173', 'Every Friday'),
('landfill', '3174', 'Every Friday'),
('landfill', '3175', 'Every Monday or Tuesday'),
('organics', '3175', 'Every Second Monday'),
('recyclable', '3175', 'Every Second Monday'),
('landfill', '3181', 'Every Thursday'),
('recyclable', '3181', 'Every Thursday'),
('landfill', '3182', 'Every Thursday'),
('recyclable', '3182', 'Every Thursday'),
('landfill', '3183', 'Every Tuesday'),
('recyclable', '3183', 'Every Tuesday'),
('landfill', '3184', 'Every Wednesday'),
('recyclable', '3184', 'Every Wednesday'),
('landfill', '3185', 'Every Wednesday'),
('recyclable', '3185', 'Every Wednesday'),
('landfill', '3186', 'Every Wednesday'),
('recyclable', '3186', 'Every Wednesday'),
('landfill', '3195', 'Every Monday'),
('landfill', '3197', 'Every Monday'),
('organics', '3197', 'Every Second Monday'),
('recyclable', '3197', 'Every Second Monday'),
('landfill', '3198', 'Every Friday'),
('organics', '3198', 'Every Second Friday'),
('recyclable', '3198', 'Every Second Friday'),
('landfill', '3199', 'Every Friday'),
('organics', '3199', 'Every Second Friday'),
('recyclable', '3199', 'Every Second Friday'),
('landfill', '3200', 'Every Friday'),
('organics', '3200', 'Every Second Friday'),
('recyclable', '3200', 'Every Second Friday'),
('landfill', '3201', 'Every Friday'),
('organics', '3201', 'Every Second Friday'),
('recyclable', '3201', 'Every Second Friday'),
('landfill', '3205', 'Every Tuesday or Friday'),
('recyclable', '3205', 'Every Tuesday or Friday'),
('landfill', '3207', 'Every Tuesday or Friday'),
('recyclable', '3207', 'Every Tuesday or Friday'),
('landfill', '3213', 'Every Second Thursday'),
('organics', '3213', 'Every Second Thursday'),
('recyclable', '3213', 'Every Second Thursday'),
('landfill', '3214', 'Every Second Friday'),
('organics', '3214', 'Every Second Friday'),
('recyclable', '3214', 'Every Second Friday'),
('landfill', '3215', 'Every Second Friday'),
('organics', '3215', 'Every Second Friday'),
('recyclable', '3215', 'Every Second Friday'),
('landfill', '3216', 'Every Second Tuesday or Wednesday'),
('organics', '3216', 'Every Second Tuesday or Wednesday'),
('recyclable', '3216', 'Every Second Tuesday or Wednesday'),
('landfill', '3217', 'Every Second Tuesday or Wednesday'),
('organics', '3217', 'Every Second Tuesday or Wednesday'),
('recyclable', '3217', 'Every Second Tuesday or Wednesday'),
('landfill', '3218', 'Every Second Thursday or Wednesday'),
('organics', '3218', 'Every Second Thursday or Wednesday'),
('recyclable', '3218', 'Every Second Thursday or Wednesday'),
('landfill', '3221', 'Every Second Thursday or Wednesday'),
('organics', '3221', 'Every Second Thursday or Wednesday'),
('recyclable', '3221', 'Every Second Thursday or Wednesday'),
('landfill', '3222', 'Every Second Monday or Tuesday'),
('organics', '3222', 'Every Second Monday or Tuesday'),
('recyclable', '3222', 'Every Second Monday or Tuesday'),
('landfill', '3225', 'Every Second Monday'),
('organics', '3225', 'Every Second Monday'),
('recyclable', '3225', 'Every Second Monday'),
('landfill', '3227', 'Every Second Tuesday'),
('organics', '3227', 'Every Second Tuesday'),
('recyclable', '3227', 'Every Second Tuesday'),
('landfill', '3231', 'Every Friday'),
('organics', '3231', 'Every Second Friday'),
('recyclable', '3231', 'Every Second Friday'),
('landfill', '3232', 'Every Friday'),
('organics', '3232', 'Every Second Friday'),
('recyclable', '3232', 'Every Second Friday'),
('landfill', '3240', 'Every Second Wednesday'),
('organics', '3240', 'Every Second Wednesday'),
('recyclable', '3240', 'Every Second Wednesday'),
('landfill', '3350', 'Every Friday'),
('recyclable', '3350', 'Every Second Friday'),
('landfill', '3352', 'Every Monday'),
('recyclable', '3352', 'Every Second Monday'),
('landfill', '3354', 'Every Thursday'),
('recyclable', '3354', 'Every Second Thursday'),
('landfill', '3355', 'Every Monday'),
('recyclable', '3355', 'Every Second Monday'),
('landfill', '3356', 'Every Friday'),
('recyclable', '3356', 'Every Second Friday'),
('landfill', '3357', 'Every Wednesday'),
('recyclable', '3357', 'Every Second Wednesday'),
('landfill', '3364', 'Every Second Wednesday'),
('organics', '3364', 'First and Third Friday of Month'),
('recyclable', '3364', 'Every Second Wednesday'),
('landfill', '3371', 'Every Second Thursday'),
('organics', '3371', 'First and Third Friday of Month'),
('recyclable', '3371', 'Every Second Thursday'),
('landfill', '3380', 'Every Thursday'),
('recyclable', '3380', 'Every Second Thursday'),
('landfill', '3381', 'Every Friday'),
('recyclable', '3381', 'Every Second Friday'),
('landfill', '3387', 'Every Friday'),
('recyclable', '3387', 'Every Second Friday'),
('landfill', '3430', 'Every Thursday'),
('recyclable', '3430', 'Every Second Thursday'),
('landfill', '3444', 'Every Thursday or Wednesday'),
('recyclable', '3444', 'Every Second Thursday or Wednesday'),
('landfill', '3448', 'Every Wednesday'),
('recyclable', '3448', 'Every Second Wednesday'),
('landfill', '3453', 'Every Friday or Wednesday'),
('recyclable', '3453', 'Every Second Friday or Wednesday'),
('landfill', '3462', 'Every Second Wednesday'),
('organics', '3462', 'First and Third Friday of Month'),
('recyclable', '3462', 'Every Second Wednesday'),
('landfill', '3463', 'Every Second Wednesday or Friday'),
('organics', '3463', 'First and Third Friday of Month'),
('recyclable', '3463', 'Every Second Wednesday or Friday'),
('landfill', '3464', 'Every Second Wednesday'),
('organics', '3464', 'First and Third Friday of Month'),
('recyclable', '3464', 'Every Second Wednesday'),
('landfill', '3465', 'Every Second Tuesday or Wednesday'),
('organics', '3465', 'First and Third Friday of Month'),
('recyclable', '3465', 'Every Second Tuesday or Wednesday'),
('landfill', '3472', 'Every Second Monday'),
('organics', '3472', 'First and Third Friday of Month'),
('recyclable', '3472', 'Every Second Monday'),
('landfill', '3515', 'Every Friday or Monday'),
('recyclable', '3515', 'Every Second Wednesday or Friday or Monday'),
('landfill', '3516', 'Every Monday'),
('recyclable', '3516', 'Every Thursday or Monday'),
('recyclable', '3517', 'Every Monday'),
('recyclable', '3518', 'Every Monday'),
('recyclable', '3520', 'Every Monday'),
('landfill', '3521', 'Every Monday'),
('recyclable', '3521', 'Every Second Monday'),
('landfill', '3522', 'Every Monday or Tuesday'),
('recyclable', '3522', 'Every Second Monday or Tuesday'),
('landfill', '3523', 'Every Second Thursday or Thursday or Tuesday or Wednesday'),
('organics', '3523', 'Every Thursday'),
('recyclable', '3523', 'Every Second Thursday or Tuesday or Wednesday'),
('recyclable', '3525', 'Every Friday'),
('recyclable', '3527', 'Every Friday'),
('recyclable', '3537', 'Every Friday'),
('landfill', '3550', 'Every Friday or Monday or Thursday or Tuesday or Wednesday'),
('organics', '3550', 'Every Second Friday or Monday or Thursday or Tuesday or Wednesday'),
('recyclable', '3550', 'Every Second Friday or Monday or Thursday or Tuesday or Wednesday'),
('landfill', '3551', 'Every Friday or Monday or Thursday or Tuesday or Wednesday'),
('organics', '3551', 'Every Second Friday or Monday or Thursday or Tuesday or Wednesday'),
('recyclable', '3551', 'Every Wednesday or Friday or Monday or Thursday or Tuesday or Wednesday'),
('landfill', '3552', 'Every Thursday'),
('organics', '3552', 'Every Second Thursday'),
('recyclable', '3552', 'Every Second Thursday'),
('landfill', '3555', 'Every Friday or Monday or Tuesday or Wednesday'),
('organics', '3555', 'Every Second Friday or Monday or Tuesday or Wednesday'),
('recyclable', '3555', 'Every Second Friday or Monday or Tuesday or Wednesday'),
('landfill', '3556', 'Every Monday or Thursday or Tuesday or Wednesday'),
('organics', '3556', 'Every Second Thursday or Tuesday or Wednesday'),
('recyclable', '3556', 'Every Second Monday or Thursday or Tuesday or Wednesday'),
('landfill', '3557', 'Every Tuesday or Wednesday'),
('recyclable', '3557', 'Every Second Tuesday or Wednesday'),
('landfill', '3558', 'Every Wednesday'),
('organics', '3558', 'Every Second Wednesday'),
('recyclable', '3558', 'Every Second Wednesday'),
('landfill', '3559', 'Every Second Thursday or Wednesday'),
('organics', '3559', 'Every Thursday'),
('recyclable', '3559', 'Every Second Thursday or Wednesday'),
('landfill', '3561', 'Every Wednesday'),
('recyclable', '3561', 'Every Second Wednesday'),
('landfill', '3570', 'Every Monday or Wednesday'),
('recyclable', '3570', 'Every Thursday or Monday or Wednesday'),
('landfill', '3571', 'Every Wednesday'),
('recyclable', '3571', 'Every Second Wednesday'),
('landfill', '3572', 'Every Wednesday'),
('recyclable', '3572', 'Every Second Wednesday'),
('recyclable', '3576', 'Every Second Friday'),
('landfill', '3607', 'Every Second Thursday'),
('organics', '3607', 'Every Thursday'),
('recyclable', '3607', 'Every Second Thursday'),
('landfill', '3608', 'Every Second Thursday'),
('organics', '3608', 'Every Thursday'),
('recyclable', '3608', 'Every Second Thursday'),
('landfill', '3610', 'Every Second Thursday'),
('organics', '3610', 'Every Thursday'),
('recyclable', '3610', 'Every Second Thursday'),
('landfill', '3612', 'Every Second Thursday'),
('organics', '3612', 'Every Thursday'),
('recyclable', '3612', 'Every Second Thursday'),
('landfill', '3629', 'Every Friday'),
('organics', '3629', 'Every Second Friday'),
('recyclable', '3629', 'Every Second Friday'),
('landfill', '3630', 'Every Second Tuesday or Tuesday'),
('organics', '3630', 'Every Tuesday or Tuesday'),
('recyclable', '3630', 'Every Second Tuesday'),
('landfill', '3631', 'Every Second Thursday or Friday'),
('organics', '3631', 'Every Thursday or Friday'),
('recyclable', '3631', 'Every Second Thursday or Friday'),
('landfill', '3634', 'Every Friday'),
('organics', '3634', 'Every Second Friday'),
('recyclable', '3634', 'Every Second Friday'),
('landfill', '3635', 'Every Friday'),
('organics', '3635', 'Every Second Friday'),
('recyclable', '3635', 'Every Second Friday'),
('landfill', '3636', 'Every Friday'),
('organics', '3636', 'Every Second Friday'),
('recyclable', '3636', 'Every Second Friday'),
('landfill', '3646', 'Every Second Tuesday or Friday'),
('organics', '3646', 'Every Tuesday or Friday'),
('recyclable', '3646', 'Every Second Tuesday or Friday'),
('landfill', '3658', 'Every Wednesday or Monday or Thursday or Tuesday'),
('organics', '3658', 'Every Second Wednesday'),
('recyclable', '3658', 'Every Second Wednesday or Monday or Thursday or Tuesday'),
('landfill', '3659', 'Every Monday'),
('recyclable', '3659', 'Every Second Monday'),
('landfill', '3660', 'Every Monday or Thursday'),
('organics', '3660', 'Every Thursday'),
('recyclable', '3660', 'Every Second Monday or Thursday'),
('landfill', '3662', 'Every Monday or Thursday or Tuesday'),
('organics', '3662', 'Every Thursday'),
('recyclable', '3662', 'Every Second Monday or Thursday or Tuesday'),
('landfill', '3663', 'Every Second Thursday'),
('organics', '3663', 'Every Thursday'),
('recyclable', '3663', 'Every Second Thursday'),
('landfill', '3664', 'Every Second Thursday'),
('organics', '3664', 'Every Thursday'),
('recyclable', '3664', 'Every Second Thursday'),
('landfill', '3665', 'Every Second Thursday'),
('organics', '3665', 'Every Thursday'),
('recyclable', '3665', 'Every Second Thursday'),
('landfill', '3666', 'Every Second Monday or Tuesday'),
('organics', '3666', 'Every Monday or Tuesday'),
('recyclable', '3666', 'Every Second Monday or Tuesday'),
('landfill', '3669', 'Every Second Tuesday or Tuesday'),
('organics', '3669', 'Every Tuesday or Tuesday'),
('recyclable', '3669', 'Every Second Tuesday'),
('landfill', '3670', 'Every Second Tuesday'),
('organics', '3670', 'Every Tuesday'),
('recyclable', '3670', 'Every Second Tuesday'),
('landfill', '3673', 'Every Second Tuesday or Tuesday or Monday'),
('organics', '3673', 'Every Tuesday or Tuesday'),
('recyclable', '3673', 'Every Second Tuesday or Monday'),
('landfill', '3675', 'Every Second Monday'),
('recyclable', '3675', 'Every Second Monday'),
('landfill', '3676', 'Every Second Friday'),
('recyclable', '3676', 'Every Second Friday'),
('landfill', '3677', 'Every Second Friday'),
('recyclable', '3677', 'Every Second Friday'),
('landfill', '3678', 'Every Second Friday'),
('recyclable', '3678', 'Every Second Friday'),
('landfill', '3682', 'Every Second Monday'),
('recyclable', '3682', 'Every Second Monday'),
('landfill', '3683', 'Every Second Wednesday'),
('recyclable', '3683', 'Every Second Wednesday'),
('landfill', '3685', 'Every Second Monday'),
('recyclable', '3685', 'Every Second Monday'),
('landfill', '3688', 'Every Second Friday'),
('organics', '3688', 'Every Friday'),
('recyclable', '3688', 'Every Second Friday'),
('landfill', '3689', 'Every Second Friday'),
('organics', '3689', 'Every Friday'),
('recyclable', '3689', 'Every Second Friday'),
('landfill', '3690', 'Every Second Friday'),
('organics', '3690', 'Every Friday'),
('recyclable', '3690', 'Every Second Friday'),
('landfill', '3691', 'Every Second Monday'),
('organics', '3691', 'Every Monday'),
('recyclable', '3691', 'Every Second Monday'),
('landfill', '3695', 'Every Second Wednesday'),
('organics', '3695', 'Every Wednesday'),
('recyclable', '3695', 'Every Second Wednesday'),
('landfill', '3713', 'Every Wednesday'),
('landfill', '3715', 'Every Second Tuesday'),
('organics', '3715', 'Every Tuesday'),
('recyclable', '3715', 'Every Second Tuesday'),
('landfill', '3719', 'Every Second Thursday'),
('organics', '3719', 'Every Thursday'),
('recyclable', '3719', 'Every Second Thursday'),
('landfill', '3720', 'Every Second Tuesday'),
('organics', '3720', 'Every Tuesday'),
('recyclable', '3720', 'Every Second Tuesday'),
('landfill', '3723', 'Every Wednesday or Tuesday'),
('recyclable', '3723', 'Every Second Tuesday'),
('landfill', '3725', 'Every Second Tuesday or Tuesday'),
('organics', '3725', 'Every Tuesday or Tuesday'),
('recyclable', '3725', 'Every Second Tuesday'),
('landfill', '3727', 'Every Tuesday'),
('organics', '3727', 'Every Second Tuesday'),
('recyclable', '3727', 'Every Second Tuesday'),
('landfill', '3728', 'Every Second Monday'),
('recyclable', '3728', 'Every Second Monday'),
('landfill', '3730', 'Every Second Monday'),
('recyclable', '3730', 'Every Second Monday'),
('landfill', '3732', 'Every Second Tuesday'),
('recyclable', '3732', 'Every Second Tuesday'),
('landfill', '3735', 'Every Second Tuesday'),
('recyclable', '3735', 'Every Second Tuesday'),
('landfill', '3737', 'Every Second Tuesday'),
('recyclable', '3737', 'Every Second Tuesday'),
('landfill', '3746', 'Every Second Wednesday'),
('recyclable', '3746', 'Every Second Wednesday'),
('landfill', '3747', 'Every Second Tuesday'),
('recyclable', '3747', 'Every Second Tuesday'),
('landfill', '3750', 'Every Monday'),
('organics', '3750', 'Every Second Monday'),
('recyclable', '3750', 'Every Second Monday'),
('landfill', '3752', 'Every Friday'),
('organics', '3752', 'Every Second Friday'),
('recyclable', '3752', 'Every Second Friday'),
('landfill', '3753', 'Every Thursday'),
('recyclable', '3753', 'Every Second Thursday'),
('landfill', '3754', 'Every Friday'),
('organics', '3754', 'Every Second Friday'),
('recyclable', '3754', 'Every Second Friday'),
('landfill', '3756', 'Every Tuesday or Friday or Thursday'),
('organics', '3756', 'Every Second Tuesday'),
('recyclable', '3756', 'Every Second Tuesday or Friday or Thursday'),
('landfill', '3757', 'Every Tuesday'),
('organics', '3757', 'Every Second Tuesday'),
('recyclable', '3757', 'Every Second Tuesday'),
('landfill', '3758', 'Every Friday or Thursday or Tuesday'),
('recyclable', '3758', 'Every Second Friday or Thursday or Tuesday'),
('landfill', '3762', 'Every Thursday'),
('recyclable', '3762', 'Every Second Thursday'),
('landfill', '3763', 'Every Monday'),
('landfill', '3764', 'Every Monday or Thursday or Wednesday'),
('recyclable', '3764', 'Every Second Monday or Thursday or Wednesday'),
('landfill', '3765', 'Every Monday'),
('landfill', '3767', 'Every Monday'),
('landfill', '3770', 'Every Friday'),
('landfill', '3775', 'Every Monday'),
('landfill', '3777', 'Every Friday'),
('landfill', '3779', 'Every Wednesday'),
('landfill', '3781', 'Every Friday'),
('landfill', '3782', 'Every Friday'),
('landfill', '3783', 'Every Friday'),
('landfill', '3785', 'Every Monday'),
('landfill', '3786', 'Every Friday'),
('landfill', '3787', 'Every Monday'),
('landfill', '3788', 'Every Monday'),
('landfill', '3789', 'Every Friday'),
('landfill', '3791', 'Every Friday'),
('landfill', '3792', 'Every Friday'),
('landfill', '3793', 'Every Monday'),
('landfill', '3795', 'Every Thursday'),
('landfill', '3797', 'Every Thursday'),
('landfill', '3799', 'Every Friday'),
('landfill', '3833', 'Every Wednesday'),
('landfill', '3895', 'Every Tuesday'),
('recyclable', '3895', 'Every Second Tuesday'),
('landfill', '3910', 'Every Friday'),
('organics', '3910', 'Every Second Friday'),
('recyclable', '3910', 'Every Second Friday'),
('landfill', '3911', 'Every Wednesday'),
('organics', '3911', 'Every Second Wednesday'),
('recyclable', '3911', 'Every Second Wednesday'),
('landfill', '3975', 'Every Monday'),
('organics', '3975', 'Every Second Monday'),
('recyclable', '3975', 'Every Second Monday'),
('landfill', '3977', 'Every Friday'),
('organics', '3977', 'Every Second Friday'),
('recyclable', '3977', 'Every Second Friday'),
('landfill', '8001', 'Every Thursday'),
('recyclable', '8001', 'Every Thursday'),
('landfill', '8002', 'Every Friday'),
('recyclable', '8002', 'Every Friday'),
('landfill', '8012', 'Every Thursday'),
('recyclable', '8012', 'Every Thursday'),
('landfill', '8045', 'Every Thursday'),
('recyclable', '8045', 'Every Thursday'),
('landfill', '8051', 'Every Thursday'),
('recyclable', '8051', 'Every Thursday'),
('landfill', '8066', 'Every Thursday'),
('recyclable', '8066', 'Every Thursday'),
('landfill', '8069', 'Every Thursday'),
('recyclable', '8069', 'Every Thursday'),
('landfill', '8070', 'Every Thursday'),
('recyclable', '8070', 'Every Thursday'),
('landfill', '8071', 'Every Thursday'),
('recyclable', '8071', 'Every Thursday'),
('landfill', '8102', 'Every Thursday'),
('recyclable', '8102', 'Every Thursday'),
('landfill', '8107', 'Every Thursday'),
('recyclable', '8107', 'Every Thursday'),
('landfill', '8111', 'Every Thursday'),
('recyclable', '8111', 'Every Thursday'),
('landfill', '8120', 'Every Thursday'),
('recyclable', '8120', 'Every Thursday'),
('landfill', '8205', 'Every Thursday'),
('recyclable', '8205', 'Every Thursday'),
('landfill', '8785', 'Every Tuesday')
