//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5120_Onboarding_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class binInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public binInfo()
        {
            this.unacceptables = new HashSet<unacceptables>();
            this.acceptables = new HashSet<acceptables>();
        }
    
        public string bin_type { get; set; }
        public string bin_color { get; set; }
        public double avg_monthly_collected { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<unacceptables> unacceptables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acceptables> acceptables { get; set; }
    }
}
