//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5120_Onboarding_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wasteCollection
    {
        public string bin_type { get; set; }
        public string postcode { get; set; }
        public string collection_time { get; set; }
    }
}
