INSERT INTO unacceptables(binInfo_bin_type, unacceptable_items) VALUES
('landfill', 'bricks or other building materials (visit Waste and recycling centre)'),
('landfill', 'car parts (visit Waste and Recycling Centre)'),
('landfill', 'chemicals'),
('landfill', 'corrosive and flammable items (visit Chemical waste disposal)'),
('landfill', 'oil'),
('landfill', 'paints and solvents (visit Chemical waste disposal)'),
('landfill', 'recyclable products (visit Household recycling)'),
('landfill', 'soil'),
('landfill', 'syringes (visit Needle and syringe disposal)'),
('landfill', 'timber'),
('landfill', 'unwrapped vacuum dust'),
('landfill', 'hot liquid or ashes'),
('organics', 'general household waste'),
('organics', 'old clothing'),
('organics', 'treated orlaminated timber'),
('organics', 'plastic bags'),
('recyclable', 'CDs'),
('recyclable', 'DVDs'),
('recyclable', 'VCR tapes'),
('recyclable', 'batteries (visit Other recycling)'),
('recyclable', 'ceramics'),
('recyclable', 'chemicals (visit Chemical waste disposal)'),
('recyclable', 'expanded polystyrene foam used in take-away coffee cups or packaging for household goods'),
('recyclable', 'food scraps (visit Home composting)'),
('recyclable', 'glass from broken glasses'),
('recyclable', 'light globes (visit Other recycling)'),
('recyclable', 'mobile phone and electronic and computer parts (visit Other recycling)'),
('recyclable', 'nappies (visit Household garbage)'),
('recyclable', 'soft plastics'),
('recyclable', 'syringes (visit Needle and syringe disposal)'),
('recyclable', 'waxed cardboard boxes'),
('recyclable', 'windows or mirrors'),
('recyclable', 'plastic bags')
