INSERT INTO wasteCollection(binInfo_bin_type, postcode, collection_time) VALUES
('landfill', '3371', 'Every Second Thursday'),
('landfill', '3143', 'Every Tuesday'),
('landfill', '3183', 'Every Tuesday'),
('landfill', '3463', 'Every Second Wednesday'),
('landfill', '3691', 'Every Second Wednesday'),
('landfill', '3465', 'Every Second Wednesday'),
('landfill', '3186', 'Every Wednesday'),
('landfill', '3472', 'Every Second Monday'),
('landfill', '3464', 'Every Second Wednesday'),
('landfill', '3691', 'Every Second Monday'),
('landfill', '3161', 'Every Tuesday'),
('landfill', '3465', 'Every Second Tuesday'),
('landfill', '3185', 'Every Wednesday'),
('landfill', '3184', 'Every Wednesday'),
('landfill', '3695', 'Every Second Wednesday'),
('landfill', '3688', 'Every Second Friday'),
('landfill', '3688', 'Every Second Monday'),
('landfill', '3688', 'Every Second Tuesday'),
('landfill', '3364', 'Every Second Wednesday'),
('landfill', '3691', 'Every Second Tuesday'),
('landfill', '8001', 'Every Thursday'),
('landfill', '3207', 'Every Friday'),
('landfill', '3207', 'Every Monday'),
('landfill', '3181', 'Every Thursday'),
('landfill', '3205', 'Every Friday'),
('landfill', '3205', 'Every Monday'),
('landfill', '3006', 'Every Monday'),
('landfill', '3182', 'Every Thursday'),
('landfill', '3182', 'Every Tuesday'),
('landfill', '3462', 'Every Second Wednesday'),
('landfill', '3690', 'Every Second Friday'),
('landfill', '3690', 'Every Second Monday'),
('landfill', '3690', 'Every Second Thursday'),
('landfill', '3690', 'Every Second Tuesday'),
('landfill', '3181', 'Every Tuesday'),
('landfill', '3689', 'Every Second Friday'),
('landfill', '3689', 'Every Second Thursday'),
('landfill', '3689', 'Every Second Tuesday'),
('recyclable', '3371', 'Every Second Thursday'),
('recyclable', '3143', 'Every Tuesday'),
('recyclable', '3183', 'Every Tuesday'),
('recyclable', '3463', 'Every Second Wednesday'),
('recyclable', '3691', 'Every Second Wednesday'),
('recyclable', '3465', 'Every Second Wednesday'),
('recyclable', '3186', 'Every Wednesday'),
('recyclable', '3472', 'Every Second Monday'),
('recyclable', '3464', 'Every Second Wednesday'),
('recyclable', '3691', 'Every Second Monday'),
('recyclable', '3161', 'Every Tuesday'),
('recyclable', '3465', 'Every Second Tuesday'),
('recyclable', '3185', 'Every Wednesday'),
('recyclable', '3184', 'Every Wednesday'),
('recyclable', '3695', 'Every Second Wednesday'),
('recyclable', '3688', 'Every Second Friday'),
('recyclable', '3688', 'Every Second Monday'),
('recyclable', '3688', 'Every Second Tuesday'),
('recyclable', '3364', 'Every Second Wednesday'),
('recyclable', '3691', 'Every Second Tuesday'),
('recyclable', '8001', 'Every Thursday'),
('recyclable', '3207', 'Every Friday'),
('recyclable', '3207', 'Every Monday'),
('recyclable', '3181', 'Every Thursday'),
('recyclable', '3205', 'Every Friday'),
('recyclable', '3205', 'Every Monday'),
('recyclable', '3006', 'Every Monday'),
('recyclable', '3182', 'Every Thursday'),
('recyclable', '3182', 'Every Tuesday'),
('recyclable', '3462', 'Every Second Wednesday'),
('recyclable', '3690', 'Every Second Friday'),
('recyclable', '3690', 'Every Second Monday'),
('recyclable', '3690', 'Every Second Thursday'),
('recyclable', '3690', 'Every Second Tuesday'),
('recyclable', '3181', 'Every Tuesday'),
('recyclable', '3689', 'Every Second Friday'),
('recyclable', '3689', 'Every Second Thursday'),
('recyclable', '3689', 'Every Second Tuesday')
